# Config relating to git
git:
  # Config for showing the log in the commits view
  log:
    # displays the whole git graph by default in the commits view (equivalent to passing the `--all` argument to `git log`)
    showWholeGraph: true
